### ISSUE TITLE
Memory leak?

### ISSUE THREAD

**Issue by pismar** [NREL/gdx-pandas#1]
Hello, 

calling the .to_dataframes method like in the example the memory usage explodes before getting to the execution end (a 1GB gdx file processing occupied 93GB of ram before the server crashed)

Same behavior with a 50 Mb file.

Am I missing something? 
Thanks
Marco

**Comment by elainethale** [comment]
Thanks for letting me know. I have seen generally performance issues with large files, which is why I implemented methods that just pull out the symbol(s) you specifically ask for (to_dataframe), but when I get a chance I will look into this memory issue more specifically.

**Comment by elainethale** [comment]
Fixed with merge of candidate Version 1.0.0 into master branch.
