### ISSUE TITLE
ValueError: can not merge DataFrame with instance of type <class 'pandas.core.series.Series'>

### ISSUE THREAD

**Issue by samarthiith** [NREL/gdx-pandas#16]
Hi!
Thanks for working on this! would be very useful. Is this ready to work?
 Here is the screen shot of the error. 
 
![image](https://user-images.githubusercontent.com/9819174/30211048-9ae03c9e-949f-11e7-8f27-42dfe8662f16.png)

**Comment by elainethale** [comment]
I have not hit that one yet. Can you send me the gdx file that triggers the error?

**Comment by elainethale** [comment]
Oh, and actually, upgrading pandas may do the trick for you.

**Comment by samarthiith** [comment]
ohh... yeah works perfectly now. I was using 0.19.2, updated to 0.20.3. Thanks a ton! 

Is there a way to read just a particular symbol? My gdx files are very large.

**Comment by elainethale** [comment]
gdxpds.to_dataframe, or use gdxpds.gdx.GdxFile with lazy_load = True. Then select your GdxSymbol by name and .load() it.
