### ISSUE TITLE
issue writing gdx file with multi-index DF

### ISSUE THREAD

**Issue by samarthiith** [NREL/gdx-pandas#20]
I am trying to write a gdx for a multi index DF, however the output has 0 dimensions (I was hoping to convert multiindex to dimensions) and only the first value is being written. 
Thanks!
 
![image](https://user-images.githubusercontent.com/9819174/34207515-13856a02-e58b-11e7-9f98-a58a13cd7996.png)
![image](https://user-images.githubusercontent.com/9819174/34207535-2f549eec-e58b-11e7-8e9c-af98e24f11c1.png)

**Comment by serdar-** [comment]
Isn't it possible to convert your DataFrame to one with single index?

**Comment by elainethale** [comment]
Yes, with .reset_index()
