### ISSUE TITLE
Another library conflict on Linux

### ISSUE THREAD

**Issue by elainethale** [NREL/gdx-pandas#21]
Working in jupyter notebooks also appears to cause a library conflict (see #18 for libstdc++.so conflict with pandas). Working with GAMS 24.8, anaconda Python 3, Ubuntu.

**Comment by serdar-** [comment]
When I want to create a set and put `df['Value'] = True` GAMS IDE shows something like "?__Str". However, if I use ctype boolean like `df['Value'] = c_bool(True)` then everything is alright. Could it be caused by this? I have GAMS 24.9 and I am running it on Linux Mint.

**Comment by elainethale** [comment]
Putting `import gdxpds` in a file and then referencing that file in the PYTHONSTARTUP environment variables loads gdxpds before everything else when running

- python
- ipython

but not when starting up a jupyter notebook. If that file is instead placed in the ~/.ipython/profile_default/startup/ directory, it does run when the ipython kernel starts up in jupyter notebook, but that is not soon enough. In this case, the kernel fails to start at all.

**Comment by elainethale** [comment]
@serdar, no, that is an unrelated issue. This issue results in gdxpds not importing at all.

**Comment by elainethale** [comment]
Using Chrome instead of Firefox made no difference.

**Comment by elainethale** [comment]
Adding ‘import gdxpds’ to the c.InteractiveShellApp.exec_lines lists in either
-	.ipython/profile_default/ipython_config.py
-	.ipython/profile_default/ipython_kernel_config.py
also produces the same behavior (multiple kernel restarts and ultimate failure to start a kernel at all).

**Comment by elainethale** [comment]
GAMS 24.8.5 and Anaconda 4.4.0 were a bad combination. I upgraded GAMS to 25.0 and Anaconda to 5.0.1 and everything is good now. According to GAMS Support, either upgrade on its own would have done the trick.
