### ISSUE TITLE
bool issue

### ISSUE THREAD

**Issue by elainethale** [NREL/gdx-pandas#25]
@serdar pointed out, 

"When I want to create a set and put df['Value'] = True GAMS IDE shows something like "?__Str". However, if I use ctype boolean like df['Value'] = c_bool(True) then everything is alright. Could it be caused by this? I have GAMS 24.9 and I am running it on Linux Mint."

And now I am seeing this as well. I will implement a backend fix ...

**Comment by serdar-** [comment]
You can check the table for boolean columns and you can write `df[bool_col] = df[bool_col].apply(c_bool)` as a straightforward solution maybe. 

Btw it is an amazing library, thanks a lot!

**Comment by elainethale** [comment]
Closed with #26 -- you're welcome @serdar- !
