### ISSUE TITLE
Citing this software

### ISSUE THREAD

**Issue by charlie0389** [NREL/gdx-pandas#27]
Love the software! Was curious if any citation is needed/wanted?

**Comment by elainethale** [comment]
Thank you! I would appreciate a citation--now there is a pypi page as well as this one: https://pypi.python.org/pypi/gdxpds/. I am currently the only contributor. Do you need any other information?

**Comment by charlie0389** [comment]
I suppose a year would be helpful as well - how long has the software been
around?

**Comment by elainethale** [comment]
Publicly released in 2016. Version 1.0.0 came out last year (2017).

**Comment by amabdallah** [comment]
@elainethale could you create a DOI for this software? It would be easier to cite into peer-review journals  
https://guides.github.com/activities/citable-code/
