### ISSUE TITLE
gdxSymbolGetDomainX failing to run

### ISSUE THREAD

**Issue by jebob** [NREL/gdx-pandas#33]
On some computers, when I run gdxpds.to_dataframes I get the error
`gdxSymbolGetDomainX could not be loaded: gdxdxlib: gdxSymbolGetDomainX cannot be found in the library`

Any ideas?

**Comment by jebob** [comment]
My working version uses gdxpds 1.0.2, my broken version uses gdxpds 1.0.4.

**Comment by elainethale** [comment]
Maybe a GAMS version/GAMS python bindings incompatibility?

**Comment by jebob** [comment]
I have identical python, GAMS and gdxpds versions. I have copied the entire Python install (including packages) across computers but no luck.

**Comment by jebob** [comment]
The only computer I can reliably replicate it on is a Windows 8 machine which is far too old.

**Comment by elainethale** [comment]
Closing since reported as not easily replicable.
