### ISSUE TITLE
Fail to run gdxpds

### ISSUE THREAD

**Issue by stephTM** [NREL/gdx-pandas#35]
Hi,

The import gdxpds command crashes Python. The error message is quite cryptic, "A problem caused the program to stop working correctly". The Debug option leads to the following message "unhandled win32 exception... Just-in-Time debugger...". I checked that I was indeed running Python 3.6.4 x64, GAMS 24.8 x64 and the GAMS 3.6 api version. Any idea...?

Thanks

**Comment by jebob** [comment]
Are you importing gams as well? That has caused issues for me in the past.

**Comment by stephTM** [comment]
No I'm not. So, I tried importing it just to see - same error message.

**Comment by elainethale** [comment]
I have had some cryptic library conflicts in the past on Linux. Conflicts between system and GAMS versions of libraries, or between GAMS and anaconda. For one of those it helped to import gdxpds before pandas.

**Comment by jebob** [comment]
We had a case where we had more than one GAMS install and GamsDirFinder was pointing at the wrong one. Deleting the bad folders (not uninstalling them) worked.

**Comment by elainethale** [comment]
In addition to pulling in the gams where request, am also checking the GAMSDIR environment variable explicitly: https://github.com/NREL/gdx-pandas/commit/162fd2646ea369754945546cca6c2c5d3621fc1b. I'm wondering if we should use where gams and which gams first, and then look in the environment variables. I'll add a new issue.
