### ISSUE TITLE
Get the GamsDataType when reading gdx and improve error msg?

### ISSUE THREAD

**Issue by amabdallah** [NREL/gdx-pandas#37]
Hello Elaine,
Thanks for the nice and useful library. I hope the NREL people are valuing your contributions to the world like in this open source tool which I think is beyond just solving some local NREL problems. 

Could you please add a parameter to get the GamsDataType when reading gdx. The backed writing function has it and it would be nice to support it to when reading. 

On a different subject, users would have an easier experience if the library has a better handle on error messages. For example, although the documentation shows the "set" or "parameter" name should be passed with single quotes  like 'my_set' when writing, passing them with no single quotes gives back a strange and unhelpful error message (see below). I wrote some dynamic code to pass many sets and parameters with names as text values in a big dataframe. It took me literally many days of back and fourth testing to figure out what that error was until I figured that I needed to programmatically add the single quotes to the passed text names like this 
`my_parameter='{}'.format(x_parameter)`

**Error message if I pass the 'my_set' or 'my_parameter' with no single quotes as part of a dataframe**    
`  File "C:\Users\Adel\Anaconda2\lib\site-packages\gdxpds\gdx.py", line 325, in write
    symbol.write(index=i)
  File "C:\Users\Adel\Anaconda2\lib\site-packages\gdxpds\gdx.py", line 795, in write
    userinfo):
  File "C:\Users\Adel\Anaconda2\lib\site-packages\gdxcc\gdxcc.py", line 519, in gdxDataWriteStrStart
    return _gdxcc.gdxDataWriteStrStart(pgdx, SyId, ExplTxt, Dimen, Typ, UserInfo)
TypeError: in method 'gdxDataWriteStrStart', argument 2 of type 'char const *'`

Users can do dummy things and its hard to predict them as a designer :)

Thanks again for this nice tool
Adel

**Comment by elainethale** [comment]
@amabdallah, regarding your request to get the GamsDataType when reading gdx files, do you have a suggested interface/function call? What function are you currently using to read gdx files? If you use the gdxpds.gdx module directly, that information should be available.

**Comment by amabdallah** [comment]
@elainethale so I'm using
dataframes = gdxpds.to_dataframes(gdx_file)

I also used this one but still does not return the GamsDataType (i.e., set or parameter)

with gdxpds.gdx.GdxFile(lazy_load=False) as f:
    f.read(gdx_file)


Do you have an example on how gdxpds.gdx returns the GamsDataType?

**Comment by elainethale** [comment]
The GamsDataType is defined at the GdxSymbol level. So f[0].data_type returns the GamsDataType for the first symbol in the file.

**Comment by amabdallah** [comment]
@elainethale thanks for! 

So I was able to get the GamsDataType for each symbol in the file with:
`symbol.data_type.name 
`
It might be useful to the users to add this line to example function use 

```
with gdxpds.gdx.GdxFile(lazy_load=False) as f:
    f.read(gdx_file)
    for symbol in f:
        symbol_name = symbol.name
        df = symbol.dataframe
        GamsDataType = symbol.data_type.name
        print("Doing work with {},{}".format(symbol_name,GamsDataType))
```

**Comment by elainethale** [comment]
API documentation for GdxSymbol is here: https://nrel.github.io/gdx-pandas/api/gdxpds.html#gdxpds.gdx.GdxSymbol.
