### ISSUE TITLE
Lazy load should not cache results

### ISSUE THREAD

**Issue by jebob** [NREL/gdx-pandas#56]
In my use case, I am trying to pick out some small and large symbols from a very large (3GB) gdx. It is too large to use to_dataframes(). Reading the GDX with lazy load is super slow, so calling to_dataframe() many times is also slow. In the end I settled for creating a Translator object and reusing it, but I discovered that the results are cached, so my large symbols have duplicated dataframes when I do anything with them.

Perhaps we should not store the symbol state by default?

**Comment by elainethale** [comment]
What particular data do you think should not be stored? I load some data so users can see what is in the file before choosing exactly which symbols to load.

**Comment by jebob** [comment]
Currently, the Translator object stores the values of the loaded symbol.

The ability to unload a symbol would work.

**Comment by elainethale** [comment]
gdxpds.read_gdx.Translator.dataframe does not appear to cache the dataframe separately in the Translator object, but it does return a copy. Is the copy problematic?

**Comment by elainethale** [comment]
I added an unload feature: https://github.com/NREL/gdx-pandas/commit/bee08e1c256ba32e3d37d63e09819dc2f9cc7559. Does that fix the issue?

**Comment by jebob** [comment]
It does not, I think the problem here is more subtle and not as I originally described.

<details>
```python
import gdxpds
import pandas as pd
import time


def read_big():
    time.sleep(10)  # RAM here 876.4MB
    print("loading")
    x = gdxpds.to_dataframes("big.gdx")
    print("loaded")
    time.sleep(10)  # RAM here 1139.9MB
    del x
    print("unloaded")
    time.sleep(10)  # RAM here 1117.2MB


def make_big():
    # This doesn't increase RAM, so pandas is not to blame
    time.sleep(10)  # RAM here 939.1MB
    print("loading")
    x = pd.DataFrame({"i": list(range(1000000)), "j": list(range(1000000)), "value": list(5 for _ in range(1000000))})
    print("loaded")
    time.sleep(10)  # RAM here 962.1MB
    del x
    print("unloaded")
    time.sleep(10)  # RAM here 939.2MB
    #gdxpds.to_gdx("big.gdx", {"big": x})


read_big()
#make_big()

```
</details>

The problem I have is that reading symbols takes more RAM than expected.
