### ISSUE TITLE
Support for multi dimensional arrays

### ISSUE THREAD

**Issue by kdheepak** [NREL/gdx-pandas#6]
@elainethale Thoughts on if this would be possible?

**Comment by elainethale** [comment]
Perhaps--in the GAMS user manual it lists "Table" alongside "Scalar" and "Parameter" as the three basic data types ... Here--I'll try real quick to write a Table to gdx.

**Comment by elainethale** [comment]
So, palm to forehead, of course. GDX files essentially store (sparse) multi-dimensional arrays all the time, just vectorized. Perhaps you just need a wrapper that goes from something like a numpy array to GDX and back?

To better explain the palm to forehead comment, when I ran this code:

```
  SETS
       I   canning plants   / SEATTLE, SAN-DIEGO /
       J   markets          / NEW-YORK, CHICAGO, TOPEKA / ;

  TABLE D(I,J)  distance in thousands of miles
                    NEW-YORK       CHICAGO      TOPEKA
      SEATTLE          2.5           1.7          1.8
      SAN-DIEGO        2.5           1.8          1.4  ;

Execute_Unload "table.gdx" D ;
```

I got a GDX file containing

----|---|----
SEATTLE | NEW-YORK | 2.5
SEATTLE | CHICAGO | 1.7
SEATTLE | TOPEKA | 1.8
SAN-DIEGO | NEW-YORK | 2.5
SAN-DIEGO | CHICAGO | 1.8
SAN-DIEGO | TOPEKA | 1.4

labeled as a "Parameter". So arrays are parameters and vice-versa ...
