### ISSUE TITLE
Different Behavior on Windows/Mac –– GdxError Expected data marker not found in GDX file.

### ISSUE THREAD

**Issue by skoeb** [NREL/gdx-pandas#67]
Writing a python script to open a ReEDS output gdx file. Trying to make the script agnostic to OS. 

On other projects, I have achieved this with a try/except block like this:

```
try:
    reeds_dict = gdxpds.to_dataframes(reeds_full_path) #first try without specifying a gams_dir
except RuntimeError:
    reeds_dict = gdxpds.to_dataframes(reeds_full_path, gams_dir=config.GAMSDIR) #if GAMS dir isn't in system path, check config file (included in .gitignore)
```

However, while this is working (in the 'try' on Windows with GAMS in the system path), it is failing in the 'except' on Mac (with gams_dir='/Applications/GAMS25.1/sysdir/')

```
  File "/Users/skoebric/Documents/NREL-GitHub/capexp-india/pcm-india/A_reeds_to_PIDG.py", line 25, in <module>
    reeds_dict = gdxpds.to_dataframes(reeds_full_path, gams_dir=config.GAMSDIR) #if GAMS dir isn't in system path, check config file (included in .gitignore)

  File "/Users/skoebric/anaconda3/lib/python3.7/site-packages/gdxpds/read_gdx.py", line 118, in to_dataframes
    dfs = Translator(gdx_file,gams_dir=gams_dir).dataframes

  File "/Users/skoebric/anaconda3/lib/python3.7/site-packages/gdxpds/read_gdx.py", line 53, in __init__
    self.__gdx.read(gdx_file)

  File "/Users/skoebric/anaconda3/lib/python3.7/site-packages/gdxpds/gdx.py", line 406, in read
    raise GdxError(self.H,"Could not open '{}'".format(filename))

GdxError: Could not open '/Users/skoebric/Documents/NREL-GitHub/capexp-india/ReEDS-2.0/E_Outputs/gdxfiles/output_july1_Base.gdx'. Expected data marker (SYMBOL_1) not found in GDX file.
```

The GDX file is the same in both cases. Trying to figure out if this is a GAMS version issue, or if the `gams_dir` argument is behaving differently than having the GAMS directory in `LD_LIBRARY_PATH`. 

I'm assuming this is my error... but has anyone seen this Expected data marker error before?

**Comment by skoeb** [comment]
gdxpds is imported before pandas

**Comment by skoeb** [comment]
The .gdx file was corrupted when moving between machines. Oops.

**Comment by Emy526** [comment]
Hello!
I am trying to open a gdx file with python and I get this error: GdxError: Could not open 'C: \\ Users \\ EMELY \\ Desktop \\ test_'. Permission denied.
I have checked the address of the folder and it is correct but I get this error

**Comment by Emy526** [comment]
I have installed gdxpds and imported it correctly but when I try to fill a gdx file with python I get this problem: Could not open 'C: \\ Users \\ EMELY \\ Desktop \\ test_'. Permission denied.
