### ISSUE TITLE
INFO: Could not find files for the given pattern(s)

### ISSUE THREAD

**Issue by fnasarias** [NREL/gdx-pandas#88]
This happens when i run `import gdxpds` though I installed it succesfully using `pip install gdxpds`

Installed GAMS 34 successfully and no problem when I run `import gams`

Running this on a Windows Anaconda environment with python = 3.8.8

Anyone experienced this?

**Comment by dcardonav** [comment]
OS=Windows 11
GAMS=36
Python=3.9

I've been having these problems with non-conda installations or base environment installation. Solved it by creating the GAMS_DIR environment and adding the C:\GAMS\36 or wherever you have GAMS installed. I'm assuming that you installed the GAMS dependencies correctly.
