### ISSUE TITLE
Error: From pandas dataframe to GDX file

### ISSUE THREAD

**Issue by erikfilias** [NREL/gdx-pandas#91]
This happens when I tried to create a gdx file from a  pandas dataframe

error:
![image](https://user-images.githubusercontent.com/8010477/180810107-b064917b-70b4-4b42-a2fb-23bcbc68ad69.png)

I imported gdxpds successfully and it was installed from pipy.

Running this on a Windows Anaconda environment with python = 3.9

Any help, please?

Thanks in advance.

**Comment by elainethale** [comment]
What does your relevant code look like?

**Comment by elainethale** [comment]
Also, it looks like you might be trying to write to a location where you don't have permissions and/or to a file that is already open in another program.
