### ISSUE TITLE
Exception: Error opening GDX

### ISSUE THREAD

**Issue by Tanvir19934** [NREL/gdx-pandas#92]
Hi,

I am trying to use GAMS Python api. Whenever I try to export I get the following error:

Exception: Error opening GDX `/Library/Frameworks/GAMS.framework/Versions/41/Resources/apifiles/Python/out.gdx`

The code is as follows. I want to export the data.

`from gams import * 
gw = GamsWorkspace()
print(gw.system_directory)
import gamstransfer as gt
import pandas as pd
m = gt.Container()
 
i = gt.Set(m, "i", records=["seattle", "san-diego"], description="supply")
j = gt.Set(m, "j", records=["new-york", "chicago", "topeka"], description="markets")
 
d = gt.Parameter(m, "d", [i, j], description="distance in thousands of miles")
 
dist = pd.DataFrame(
    [
        ("seattle", "new-york", 2.5),
        ("seattle", "chicago", 1.7),
        ("seattle", "topeka", 1.8),
        ("san-diego", "new-york", 2.5),
        ("san-diego", "chicago", 1.8),
        ("san-diego", "topeka", 1.4),
    ],
    columns=["from", "to", "thousand_miles"],
)

d.setRecords(dist)
 
m.write("out.gdx")`

If I leave out m.write("out.gdx"), I get yet another error-

dlopen(/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/_gams2numpy.so, 0x0002): tried: '/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/_gams2numpy.so' (mach-o file, but is an incompatible architecture (have (x86_64), need (arm64e)))

Any help is appreciated!

**Comment by jebob** [comment]
Hello!

You are calling the GAMS API directly here. gdx-pds is a wrapper around the GAMS API that makes it easier to call. This code does the equivalent of what you're asking using gdx-pds:

```python
import gdxpds
import pandas as pd


dist = pd.DataFrame(
    [
        ("seattle", "new-york", 2.5),
        ("seattle", "chicago", 1.7),
        ("seattle", "topeka", 1.8),
        ("san-diego", "new-york", 2.5),
        ("san-diego", "chicago", 1.8),
        ("san-diego", "topeka", 1.4),
    ],
    columns=["from", "to", "thousand_miles"],
)

gdxpds.to_gdx({"d": dist}, "out.gdx")
```
